version: '3.7'

services:

  snack-webserver:
    networks:
      - enode
    image: nginx:alpine
    volumes:
      - ../source:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl/
    ports:
      - '8063:80'
    depends_on:
      - snack-php

  snack-php:
    networks:
      - enode
    build: php
    environment:
      - XDEBUG_CONFIG=remote_host=172.18.0.1
    volumes:
      - ../source:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./tmp:/tmp
    depends_on:
      - mysql

  mysql:
    networks:
      - enode
    image: mariadb:10.4.12
    volumes:
      - storage-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=app
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

volumes:
  storage-db:

networks:
  enode:
    external:
      name: enode
